### ISSUE TITLE
Needs a top-level 'kafka' directory

### ISSUE THREAD

**Issue by whiteinge** [saltstack-formulas/kafka-formula#1]
Everything here looks great for a first-rev. The only needed change is to move all the files in the root dir under a top-level 'kafka' directory so that the repo can be included in Salt's GitFS or file_roots settings.

[Docs describing that directory structure](https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#repository-structure).

**Comment by blbradley** [comment]
Eeeek! I noticed this while integrating the formula.

**Comment by blbradley** [comment]
I had it fixed in my account's repo right after you pushed the commits. Mind doing a force push with my repo's commits to preserve history? I promise this will only happen once.

**Comment by whiteinge** [comment]
GitHub disabled force-pushes for us at the Organization level as a special request so I'm afraid even admins can't do that. (I double-checked just now and I don't have access.)

This will need to be done as a commit against the existing history.

**Comment by blbradley** [comment]
Ok! Thanks for checking.
